apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Taskcluster
  region: ap-south-1

nodeGroups:
   - name: Node1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: default
   - name: Node2
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: default
   
